# Podman compatible

services:
  redis:
    image: docker.io/redislabs/redismod
    ports:
      - '6379:6379'
    # volumes:
    #   - redis_data:/data

  app:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    ports:
      - '127.0.0.1:8822:22'
    volumes:
      - .:/code
    depends_on:
      - redis

# volumes:
#   redis_data: